name: dart_time
description: A Very Good dart_time library to work with time, provide date, time, duration, and more.
homepage: https://mattiapispisa.github.io/
repository: https://github.com/mattiaPispisa/dart_time
topics: [time, date, duration, range]

version: 0.1.0

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  meta: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.4
  path: ^1.9.1
  test: ^1.26.2
  very_good_analysis: ^10.0.0
  yaml: ^3.0.0
