name: dart_time
description: A Very Good Dart Time library to work with time, provide date, time, duration, and more.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  meta: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
