name: Monorepo CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dart_time:
    uses: ./.github/workflows/dart_package.yaml
    with:
      working_directory: .
      min_coverage: 100
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}